name: Build tenha fibra

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clear caches and remove node_modules
      run: npm cache clean --force && rm -rf node_modules

    - name: Install dependencies
      run: npm install --force

    - name: Build
      run: npm run build

    - name: Commit files
      run: 
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Build and commit dist files" || echo "No changes to commit"
          git push
