name: Build tenha fibra
permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clear caches and remove node_modules
      run: npm cache clean --force && rm -rf node_modules

    - name: Install dependencies
      run: npm install --force

    - name: Build
      run: npm run build
      
    - name: Adicionar e cometer os arquivos de construção
      run: |
        git config --global user.email "ederson.gsouza96@gmail.com"
        git config --global user.name "git-osouza"
        git remote set-url origin https://git-osouza:${{ secrets.TOKEN_TESTE_DEPLOY }}@github.com/git-osouza/tenhaFibraDeploy.git
        
        # Verifica se o repositório existe
        curl -s -o /dev/null -w "%{http_code}" https://github.com/git-osouza/tenhaFibraDeploy.git
        if [ $? -ne 200 ]; then
          echo "Erro: O repositório 'tenhaFibraDeploy' não foi encontrado."
          exit 1
        fi
        
        git add .
        git commit -m "Atualizar arquivos de construção [skip ci]"
        git push origin HEAD:master
    env:
      TOKEN_TESTE_DEPLOY: ${{ secrets.TOKEN_TESTE_DEPLOY }}
