name: Build tenha fibra

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clear caches and remove node_modules
      run: npm cache clean --force && rm -rf node_modules

    - name: Install dependencies
      run: npm install --force

    - name: Build
      run: npm run build
      
    - name: Adicionar e cometer os arquivos de construção
      run: |
        git config --local user.email "ederson.gsouza96@gmail.com"
        git config --local user.name "git-osouza"
        git remote set-url origin https://github.com/git-osouza/tenhaFibraDeploy.git
        git add .
        git add dist
        git commit -m "Atualizar arquivos de construção [skip ci]"
        git push https://${{ secrets.TOKEN_TESTE_DEPLOY }}:${{ secrets.PAT }}@github.com/git-osouza/tenhaFibraDeploy.git HEAD:master
