name: Build tenha fibra

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clear caches and remove node_modules
      run: npm cache clean --force && rm -rf node_modules

    - name: Install dependencies
      run: npm install --force

    - name: Build
      run: npm run build

    - name: Verificar mudanças no campo version do package.json
      id: check_version_changes
      run: |
        if git diff --quiet HEAD^..HEAD -- package.json; then
          echo "Sem mudanças no arquivo package.json"
        else
          if git diff --exit-code --name-only HEAD^..HEAD | grep -q 'package.json'; then
            if jq -e '.version' package.json > /dev/null; then
              if jq -e '.version' package.json | grep -q 'new_version'; then
                echo "::set-output name=version_changed::true"
              fi
            fi
          fi
        fi
                
    - name: Add e commit dos arquivos de build
      if: steps.check_version_changes.outputs.version_changed == 'true'
      uses: EndBug/add-and-commit@v7
      with:
        message: "Atualizar arquivos de build [skip ci]"
        add: "dist"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
