name: Build tenha fibra

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clear caches and remove node_modules
      run: npm cache clean --force && rm -rf node_modules

    - name: Install dependencies
      run: npm install --force

    - name: Build
      run: npm run build
      
    - name: Clonar repositório deploy
      run: |
        git clone https://git-osouza:${{ secrets.TOKEN_TESTE_DEPLOY }}@github.com/git-osouza/tenhaFibraDeploy.git deploy
        mv dist/app-tenha-fibra/* deploy/
        mv /dist/app-tenha-fibra/.* deploy/ 2>/dev/null || :
        rm -rf deploy/dist/app-tenha-fibra
        cd deploy
    
    - name: Commit e push dos arquivos de construção
      run: |
        cd deploy
        git config --local user.email "ederson.gsouza96@gmail.com"
        git config --local user.name "git-osouza"
        git add .
        git commit -m "Atualizar arquivos de construção [skip ci]"
        git push origin HEAD:master
      env:
        TOKEN_TESTE_DEPLOY: ${{ secrets.TOKEN_TESTE_DEPLOY }}
